# Erasmus Mundus Scholarship Prediction Project

**Life cycle of Machine learning Project**

* Understanding the Problem Statement
* Data Collection
* Exploratory data analysis
* Data Cleaning
* Data Pre-Processing
* Model Training
* Choose best model

---

## About
The Erasmus Mundus Joint Master (EMJM) is a prestigious, integrated, international study programme, jointly delivered by an international consortium of higher education institutions. The scholarship is highly competitive and depends on various criteria including academic records, test scores (GRE, TOEFL, IELTS), work experience, statement of purpose (SOP), letter of recommendation (LOR), and other extracurricular achievements.

## 1) Problem statement.

* Every year, thousands of students apply for the Erasmus Mundus Scholarship, making the selection process highly competitive and rigorous.
* The selection committee needs to review a huge volume of applications. A Machine Learning model can help shortlist highly potential candidates based on historical data.

**In this project we are going to use the data given to build a Classification model:**

* This model is to predict if a student will be awarded the scholarship or not based on the given dataset.
* This can be used to recommend a suitable profile for applicants and help them understand which criteria influence the final decision.

## 2) Data Collection.

* The Dataset is collected from previous applicants' profiles and outcomes.
* The data consists of 1000 Rows and 17 Columns.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")

%matplotlib inline

In [ ]:
df = pd.read_csv('Graduate.csv')

In [18]:
df.head()

,GRE_Score,TOEFL_Score,IELTS_Score,CGPA,University_Rating,SOP,LOR,Research,Publications,Work_Experience_Months,Internship,Leadership_Score,Awards_Count,Country,Target_Program,Graduation_Year,Scholarship_Awarded
0,295.0,96.0,7.5,2.93,2,4.9,1.7,0,1,8,No,5,0,Nepal,EMJM Cyber,2024,No
1,340.0,119.0,9.0,3.76,3,4.1,1.7,0,1,31,Yes,4,0,Pakistan,EMJM Cyber,2025,No
2,336.0,96.0,7.5,3.12,1,3.2,1.8,1,2,29,Yes,4,1,Bangladesh,EMJM Cyber,2022,No
3,337.0,108.0,8.0,2.11,4,3.4,1.3,0,0,35,Yes,3,0,Bangladesh,EMJM DS,2025,No
4,323.0,98.0,7.5,3.40,1,1.1,1.3,0,1,16,Yes,2,0,India,EMJM DS,2025,No

In [19]:
df.describe()

,GRE_Score,TOEFL_Score,IELTS_Score,CGPA,University_Rating,SOP,LOR,Research,Publications,Work_Experience_Months,Leadership_Score,Awards_Count,Graduation_Year
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,315.840000,106.459000,8.064500,3.027160,3.053000,2.997000,3.014400,0.517000,1.119000,18.814000,4.552000,0.333000,2023.473000
std,15.083432,8.449954,0.557585,0.582774,1.421341,1.163239,1.163136,0.499961,0.908661,8.896097,1.388966,0.475749,1.124516
min,290.000000,92.000000,7.000000,2.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,2022.000000
25%,303.000000,99.000000,7.500000,2.530000,2.000000,2.000000,2.000000,0.000000,0.000000,13.000000,4.000000,0.000000,2022.000000
50%,316.000000,107.000000,8.000000,3.025000,3.000000,3.000000,3.000000,1.000000,1.000000,19.000000,5.000000,0.000000,2023.000000
75%,329.000000,114.000000,8.500000,3.550000,4.000000,4.000000,4.000000,1.000000,2.000000,25.000000,6.000000,1.000000,2024.000000
max,340.000000,120.000000,9.000000,4.000000,5.000000,5.000000,5.000000,1.000000,4.000000,36.000000,8.000000,2.000000,2025.000000